server:
  port: 8188
  servlet:
    context-path: /web-market-auth
spring:
  datasource:
    url: jdbc:postgresql://localhost:5439/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: false
jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g
  lifetime: 36000000
